name: 'calder & hollis'
favicon: null
layout_spectrum: 0.5248
typography_spectrum: 0.60304
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.86402
  lightness: 0.782094
  saturation: 0.5
  rhythmicContrast: 0.823479
purpose:
  - name: null
    item: null
    url: null
