favicon: null
name: 'calder & hollis'
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose:
  - name: null
    url: null
    item: null
color:
  saturation: 1
  brandStrength: 0.86402
  rhythmicContrast: 0.823479
  brandColors:
    - '#c0c1c3'
    - '#0c0e09'
    - '#2e3e42'
    - '#4f6667'
    - '#95774c'
  lightness: 0.782094
typography_spectrum: 0.38263
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 1
analytics:
  twitter: null
  google: null
  facebook: null
