name: 'calder & hollis'
favicon: null
layout_spectrum: 0
typography_spectrum: 0.38263
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c0c1c3'
    - '#0c0e09'
    - '#2e3e42'
    - '#4f6667'
    - '#95774c'
  brandStrength: 0.86402
  lightness: 0.782094
  saturation: 1
  rhythmicContrast: 0.823479
purpose:
  - name: null
    item: null
    url: null
